### ISSUE TITLE
[Client] 로그인 페이지 구현

### ISSUE THREAD

**Issue by hihello1123** [codestates/Scrooge-client#12]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: feature login component

### TODO
1. [ ] 로그인 페이지 구현 및 SCSS 작성
2. [ ] Axios 사용하여 서버에서 토큰 받아오기
3. [ ] 받은 토큰 Redux로 상태 저장

### Estimated time
> Pick one
### Labels
- Estimated time: `E:3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
