### ISSUE TITLE
[Client] 일별페이지 지출 내역 리스트 카테고리 필터 & 날짜 별 정렬 & 검색 기능 추가

### ISSUE THREAD

**Issue by solheee** [codestates/Scrooge-client#17]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 내역이 늘어남에 따라 스크롤도 늘어남, 페이지 나누기

### TODO
1. [x] 메모 검색 기능
2. [x] 카테고리 필터 기능
3. [x] 날짜 순 정렬 기능

### Estimated time
> Pick one
### Labels
- Estimated time: `E:3h`
- Group : `client`
- Sprint: `Sprint 3`
- Urgency:  `Low`
