### ISSUE TITLE
[Client] 랜딩 페이지 구현

### ISSUE THREAD

**Issue by hihello1123** [codestates/Scrooge-client#6]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: feature landing and login page

### TODO
1. [x] 랜딩 페이지 렌더링
2. [x] 임시 로그인 버튼 구현
3. [x] 임시 로그인 버튼 클릭시 모달창으로 로그인 컴포넌트 구현
### Estimated time
> Pick one
### Labels
- Estimated time: `E:3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
