### ISSUE TITLE
[Client] 일별 페이지 상단 구현

### ISSUE THREAD

**Issue by hihello1123** [codestates/Scrooge-client#7]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Making login page from Landing page

### TODO
1. [x] Nav bar 반응형 구현
2. [x] 서버로부터 데이터 받아서 표시
2. [x] 상단부 전체 통계 컴포넌트 구현

### Estimated time
> Pick one
### Labels
- Estimated time: `E:3h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
