### ISSUE TITLE
[Client] 프로필 컴포넌트 

### ISSUE THREAD

**Issue by solheee** [codestates/Scrooge-client#8]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 프로필 컴포넌트, 유저 프로필 받아오기 구현

### TODO
1. [x] 프로필 컴포넌트 구현 및 CSS 스타일링
2. [x] 리덕스, axios로 서버에 유저 프로필 요청
3. [x] 로그인 상태 관리

### Estimated time
> Pick one
### Labels
- Estimated time: `E:2h`
- Group : `client`
- Sprint: `Sprint 2`
- Urgency: `High`
